# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170413_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='d_a_pop',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='d_d_pop',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='d_lat',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='d_lon',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='d_nr_bus',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='d_nr_hea',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='d_nr_sub',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='d_p_pop',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='d_xcoord',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='d_ycoord',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='osrm_dist',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='osrmminsdelta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='p_a_pop',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='p_d_pop',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='p_lat',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='p_lon',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='p_nr_bus',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='p_nr_hea',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='p_nr_sub',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='p_p_pop',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='p_xcoord',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='p_ycoord',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=13, null=True),
        ),
    ]
