# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170413_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='d_bctcb2010',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='p_bctcb2010',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='tripid',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
