# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_trips_level_0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='d_lon',
            new_name='d_lng',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='p_lon',
            new_name='p_lng',
        ),
    ]
