# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170502_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='dozip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='dropzip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='pickzip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='puzip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
