# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 19:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170502_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropoff_locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripid', models.BigIntegerField(blank=True, default=0, null=True)),
                ('p_lat', models.FloatField(blank=True, default=0, null=True)),
                ('p_lng', models.FloatField(blank=True, default=0, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.trips')),
            ],
        ),
        migrations.CreateModel(
            name='pickup_locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripid', models.BigIntegerField(blank=True, default=0, null=True)),
                ('p_lat', models.FloatField(blank=True, default=0, null=True)),
                ('p_lng', models.FloatField(blank=True, default=0, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.trips')),
            ],
        ),
    ]
