# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 20:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170511_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ada_subway_stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartodb_id', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('objectid', models.IntegerField()),
                ('stop_id', models.CharField(max_length=80)),
                ('stop_name', models.CharField(max_length=80)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('geoid', models.IntegerField()),
                ('namelsad', models.CharField(max_length=80)),
                ('stop_id2', models.CharField(max_length=80)),
                ('trains', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
