# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 18:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ada_subway_stations'),
    ]

    operations = [
        migrations.CreateModel(
            name='nyct_subway_stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartodb_id', models.IntegerField()),
                ('objectid', models.IntegerField()),
                ('stop_id', models.CharField(max_length=80)),
                ('stop_name', models.CharField(max_length=80)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('name_cur', models.CharField(max_length=80)),
                ('routes_wkd', models.CharField(max_length=80)),
                ('routes_off', models.CharField(max_length=80)),
                ('routes_all', models.CharField(max_length=80)),
                ('name_prop', models.CharField(max_length=80)),
                ('route_lbl', models.CharField(max_length=80)),
                ('ada_access', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
