# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 21:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_nyc_odp_census_tracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyc_odp_census_tracts',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
