# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 17:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_nyc_odp_zctas'),
    ]

    operations = [
        migrations.CreateModel(
            name='nyc_odp_zctas_remove_building_zips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=5)),
                ('bldgzip', models.CharField(max_length=1)),
                ('po_name', models.CharField(max_length=28)),
                ('population', models.FloatField()),
                ('area', models.FloatField()),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=20)),
                ('st_fips', models.CharField(max_length=2)),
                ('cty_fips', models.CharField(max_length=3)),
                ('url', models.CharField(max_length=200)),
                ('shape_area', models.FloatField()),
                ('shape_len', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='nyc_odp_zctas',
        ),
    ]
