# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_medical_centers'),
    ]

    operations = [
        migrations.CreateModel(
            name='trips_pickup_dropoff_tracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripid', models.BigIntegerField(blank=True, default=0, null=True)),
                ('pickup_tract', models.CharField(max_length=254)),
                ('dropoff_tract', models.CharField(max_length=254)),
            ],
        ),
    ]
